var ENGINE_SETTINGS = {
	DISABLE_FULL_BATTLE_SCENE: false,
	BATTLE_SCENE: {
		SPRITES_FILTER_MODE: "NEAREST", // NEAREST or TRILINEAR
	},
	KEEP_ENEMY_SPRITE_ORIENTATION: false,
	ENEMY_TARGETING_FORMULA: "Math.min(hitrate, 1) * damage" 
}